---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html
    - /bin/cp -r * $DEPLOYPATH
    - cd $DEPLOYPATH
    - composer install --no-dev --prefer-dist
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
